apiVersion: v1
kind: Service
metadata:
  name: nginx-deployment
  namespace: rolling
  labels:
    app: nginx-deployment
spec:
  ports:
  - protocol: TCP
    port: 80
  selector:
    app: nginx-deployment