apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
    - name: nginx-container
      image: nginx
      # Var d'environnemnent
      envFrom:
        # référence au configmap
        - configMapRef:
            name: nginx-config