apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod2
spec:
  containers:
    - name: nginx-container
      image: nginx
      volumeMounts:
      - name: config-volume
      mountPath: /etc/config
      volumes:
      - name: config-volume
        configMap:
          name: nginx-config