apiVersion: v1
kind: Pod
metadata:
  name: private-reg
spec:
  containers:
  - name: private-reg-container
    image: smontri/mynginx:alpine
  imagePullSecrets:
  - name: regcred
  imagePullPolicy: Always